### ISSUE TITLE
Auto test 

### ISSUE THREAD

**Issue by majorsilence** [majorsilence/My-FyiReporting#84]
Auto test code with nunit and fitnesse.

Auto generate release packages and run all tests on them.

**Comment by chripf** [comment]
Could AppVeyor run the existing tests? I do not see any test results there...

**Comment by majorsilence** [comment]
Yes.  That would be best.  Below is the current appveyor config.   It needs to be modified for tests.

```yml
version: 1.0.{build}
nuget:
  account_feed: true
  project_feed: true
build_script:
- cmd: >-
    cd Release-Builds

    build-fyi-release-dot-net-4.bat

    build-nuget-packages.bat
artifacts:
- path: Release-Builds/build-output/*.zip
- path: Release-Builds/build-output/*.nupkg
```

**Comment by chripf** [comment]
Just gave it a shot on my fork. This is running the tests:

```
version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore MajorsilenceReporting.sln
build:
  project: MajorsilenceReporting.sln
  verbosity: minimal
```

It is not using the buildscripts thou.
